import {Dimensions, StyleSheet} from 'react-native';
import {colors, fonts} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.theme._300,
  },
  brandName: {
    fontSize: fonts.size.h5,
    fontFamily: fonts.type.bold,
    color: colors.dark,
  },
  topContainer: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height * 0.2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 18,
  },
  bottomContainer: {
    backgroundColor: colors.theme._100,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height * 0.8,
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
  },
  containerHeading: {
    fontSize: fonts.size.h5,
    fontFamily: fonts.type.medium,
    color: colors.dark,
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 30,
  },
  profilePreviewCard: {
    width: Dimensions.get('window').width * 0.8,
    flexDirection: 'row',
    padding: 15,
    gap: 5,
    borderRadius: 16,
    backgroundColor: '#FFEFD0',
    shadowColor: 'rgba(0, 0, 0, 0.20)',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 4,
  },
  displayName: {
    fontSize: fonts.size.label,
    fontFamily: fonts.type.bold,
    color: colors.dark,
  },
  iconBg: {
    backgroundColor: colors.theme._300,
    borderRadius: 50,
    padding: 5,
    width: 35,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuContainer: {
    width: Dimensions.get('window').width * 0.8,
    marginVertical: 35,
    paddingVertical: 30,
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: colors.theme._300,
    borderRadius: 15,
    gap: 18,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.theme._200,
    borderRadius: 13,
    width: Dimensions.get('window').width * 0.85,
    padding: 12,
    marginBottom: 25,
    shadowColor: 'rgba(0, 0, 0, 0.20)',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 4,
  },
  menuIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  menuTextContainer: {
    flex: 1,
    justifyContent: 'space-between',
    marginLeft: 12,
    height: 75,
  },
  menuItemText: {
    fontSize: fonts.size.label,
    fontFamily: fonts.type.bold,
    color: colors.dark,
  },
  tagline1: {
    fontSize: fonts.size.label,
    fontFamily: fonts.type.regular,
    color: 'rgba(0, 0, 0, 0.90)',
  },
  tagline2: {
    fontSize: fonts.size.label,
    fontFamily: fonts.type.medium,
    color: colors.theme._300,
    textAlign: 'center',
  },
  button: {
    height: 20,
    paddingHorizontal: 12,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: colors.theme._300,
  },
  signInButton: {
    backgroundColor: colors.theme._300,
  },
  buttonText: {
    color: colors.dark,
    fontFamily: fonts.type.regular,
    fontSize: fonts.size.caption,
  },
  error: {
    color: colors.error,
    fontFamily: fonts.type.regular,
    fontSize: fonts.size.label,
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.80)',
  },
  modalContent: {
    width: Dimensions.get('window').width * 0.8,
    backgroundColor: colors.theme._200,
    padding: 20,
    borderRadius: 20,
    alignItems: 'center',
  },
  modalHeading: {
    fontSize: fonts.size.h5,
    fontFamily: fonts.type.bold,
    color: colors.dark,
    marginBottom: 12,
  },
  input: {
    width: '100%',
    padding: 12,
    backgroundColor: colors.theme._200,
    borderRadius: 10,
    marginBottom: 12,
  },
  reviewInput: {
    width: '100%',
    padding: 12,
    backgroundColor: colors.theme._100,
    borderRadius: 10,
    marginBottom: 12,
    height: 100,
    textAlignVertical: 'top',
    marginVertical: 12,
  },
  reviewButton: {
    height: 36,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginVertical: 12,
    flexDirection: 'row',
    gap: 6,
    backgroundColor: colors.theme._300,
  },
  reviewButtonText: {
    color: colors.dark,
    fontFamily: fonts.type.medium,
    fontSize: fonts.size.p,
  },
});
